### PR TITLE
use white logo for mobile nav

### PR DESCRIPTION
**Pull request by bolandrm**

### CODE REVIEW

**Comment by ryw** [comment]
Logo looks stretched :(

**Comment by ryw** [comment]
@bolandrm

**Comment by bolandrm** [comment]
@ryw That's the asset that was provided to us - do you have a white-text version of the logo that is the correct aspect ratio?

**Comment by ryw** [comment]
I don't, but it's def stretched. ask whoever gave to you to fix?

https://github.com/tembo-io/website/blob/510fefc5448a04518f1c7bc03b907935ce467f9f/static/img/title-logo.svg
https://github.com/tembo-io/website/blob/510fefc5448a04518f1c7bc03b907935ce467f9f/static/img/title-logo-white.svg

**Comment by bolandrm** [comment]
We've requested a corrected version of the logo

**Comment by ryw** [comment]
@bolandrm want to ask again?

**Comment by bolandrm** [comment]
@ryw I got the updated logo but Github is not letting me push.  Has my access changed?

**Comment by samay-sharma** [comment]
@DarrenBaldwin07 : Can you look at this and either fix and merge or close?

**Pull request closed without merging**
