### PR TITLE
Feature/break postgres guides

### PR DESCRIPTION
**Pull request by nishilfaldu**
https://linear.app/tembo/issue/CLOUD-100/website-break-postgres-guides-out-into-its-own-section

### CODE REVIEW

**Comment by sjmiller609** [comment]
I would do in this order instead: basic, extensions, advanced

**Comment by samay-sharma** [comment]
@nishilfaldu : Let's create a section for connecting and move the connection guides there and then merge this. Is there anything pending?

**Review by samay-sharma — APPROVED** [review]

**Comment by nishilfaldu** [comment]
> @nishilfaldu : Let's create a section for connecting and move the connection guides there and then merge this. Is there anything pending?

Can do that. Nothings pending and should be good to go! Thanks!

**Comment by ryw** [comment]
i checked this, looks good, merging

**Pull request merged**
