### PR TITLE
Revert "Revert "add pp supply mono for nav and headline""

### PR DESCRIPTION
**Pull request by hmillison**
@ryw i am requesting your assistance here, this commit that adds a new font for the pages build for production fine locally, but seems to be failing in AWS Amplify. Since i don't think i can access the build logs in Amplify, i wanted to know if you could take a look at what error is occuring there?

See failed build here: https://github.com/tembo-io/website/runs/14504028944

### CODE REVIEW

**Comment by ryw** [comment]
@sjmiller609 can you check?

**Comment by sjmiller609** [comment]
```
                                 > docusaurus build
2023-06-23T13:59:41.113Z [INFO]: [INFO] [en] Creating an optimized production build...
2023-06-23T13:59:42.223Z [INFO]: [info] [webpackbar] Compiling Client
2023-06-23T13:59:42.246Z [INFO]: [info] [webpackbar] Compiling Server
2023-06-23T14:00:00.252Z [INFO]: [success] [webpackbar] Client: Compiled with some errors in 18.03s
2023-06-23T14:00:00.259Z [INFO]: Error: Can't resolve '@site/static/fonts/PPSupplyMono-variable.ttf' in '/codebuild/output/src611410942/src/website/src/css'
                                 Error: Can't resolve '@site/static/fonts/PPSupplyMono-variable.ttf' in '/codebuild/output/src611410942/src/website/src/css'
                                 at runMicrotasks (<anonymous>)
                                 -- inner error --
                                 Error: Can't resolve '@site/static/fonts/PPSupplyMono-variable.ttf' in '/codebuild/output/src611410942/src/website/src/css'
                                 at runMicrotasks (<anonymous>)
                                 Generated code for /codebuild/output/src611410942/src/website/node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[6].use[1]!/codebuild/output/src611410942/src/website/node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[6].use[2]!/codebuild/output/src611410942/src/website/src/css/custom.css
2023-06-23T14:00:00.259Z [WARNING]: [ERROR] Client bundle compiled with errors therefore further build is impossible.
2023-06-23T14:00:00.284Z [ERROR]: !!! Build failed
2023-06-23T14:00:00.284Z [ERROR]: !!! Non-Zero Exit Code detected
2023-06-23T14:00:00.284Z [INFO]: # Starting environment caching...
2023-06-23T14:00:00.285Z [INFO]: # Uploading environment cache artifact...
2023-06-23T14:00:00.550Z [INFO]: # Uploaded environment cache artifact
2023-06-23T14:00:00.550Z [INFO]: # Environment caching completed
```

**Comment by sjmiller609** [comment]
I'm checking if there is a way to reproduce this issue locally for better troubleshooting of this issue and following build issues

**Comment by sjmiller609** [comment]
I'm not sure if this is related, when I do a refresh build I get this warning
```

[WARNING] {"moduleIdentifier":"/Users/steven/coredb/website/node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[7].use[1]!/Users/steven/coredb/website/node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[7].use[2]!/Users/steven/coredb/website/src/components/Footer/styles.module.css","moduleName":"./src/components/Footer/styles.module.css.webpack[javascript/auto]!=!./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[7].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[7].use[2]!./src/components/Footer/styles.module.css","message":"Module Warning (from ./node_modules/postcss-loader/dist/cjs.js):\n(84:3) Nested CSS was detected, but CSS nesting has not been configured correctly.\nPlease enable a CSS nesting plugin *before* Tailwind in your configuration.\nSee how here: https://tailwindcss.com/docs/using-with-preprocessors#nesting\n\nCode:\n  .link {\n    @apply px-6;\n  }\n","compilerPath":"client"}

```

**Comment by sjmiller609** [comment]
> I'm checking if there is a way to reproduce this issue locally for better troubleshooting of this issue and following build issues

I haven't found a great way to do this . I could try replacing the build environment of AWS Amplify with a Dockerfile I define like [this](https://docs.aws.amazon.com/amplify/latest/userguide/custom-build-image.html), but that's just some extra work.

I think it's just that AWS build environment doesn't have the font you're adding?

Please let me know if you do not have enough to be unblocked, if this is a recurring issue, I can do the custom build environment option.

@hmillison

**Comment by hmillison** [comment]
Thanks for the information @sjmiller609 - i will try some more attempts to see if it fixes the issue. I'm wondering if for some reason Amplify doesn't know to copy files with the `.ttf` file extension because we're referencing other files in the `/static` directory from CSS and having no problems.

I think the other rebuild error is a red herring, but it doesn't hurt to fix it to eliminate confusion!

**Comment by hmillison** [comment]
@sjmiller609 @ryw i changed the target branch of this pull request to `main` so i could test if changes to the css fix the build in amplify. For some reason, it seems like the action is not running to build this branch. Any ideas?

**Comment by sjmiller609** [comment]
@hmillison another thing I could do is let you change the amplify build settings, and/or I could get you access to AWS. Let me know and thank you, the site is looking sweet in your preview enviroment.

**Pull request merged**
